/**
 * Revision History - newest revisions first
 ***********************************************************************
 * 
 * 
 * 
 * 12/26/18 - Some documentation added and cleaned up (aapplin)
 * 8/15/17 - Rewritten in Java (except for the 3 enhancement methods aapplin)
 * 2005 - Original version written in C++ by Sharon Stansfield at Ithaca 
 *    college for CSC171
 */
package pgmImage;

import javax.swing.JFrame;

/**
 * GUI front end to the Image Processing Problem
 * WARNING -- do not change any existing code.  You will code one 
 * method as homework, one method as a lab exercise and one 
 * method as a project.
 * @author aapplin
 */
public class ImageFrame extends javax.swing.JFrame {

    /**
     * Creates new form ImageFrame
     */
    public ImageFrame() {
        initComponents();
        fileErrorLabel.setVisible(false);
        displayButton.setVisible(false);
        smoothButton.setVisible(false);
        linearButton.setVisible(false);
        histEqButton.setVisible(false);
        startOverButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        startOverButton = new javax.swing.JButton();
        linearButton = new javax.swing.JButton();
        smoothButton = new javax.swing.JButton();
        histEqButton = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        fileErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        startOverButton.setText("Start Over");
        startOverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startOverButtonMouseClicked(evt);
            }
        });

        linearButton.setText("Linear Enhancement");
        linearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linearButtonMouseClicked(evt);
            }
        });

        smoothButton.setText("Smoothing");
        smoothButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smoothButtonMouseClicked(evt);
            }
        });

        histEqButton.setText("Histogram Equalization");
        histEqButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                histEqButtonMouseClicked(evt);
            }
        });

        displayButton.setText("Display Original Image");
        displayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayButtonMouseClicked(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadButtonMouseClicked(evt);
            }
        });

        fileNameLabel.setText("File to Process");

        

        fileErrorLabel.setText("File not found");

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayButton)
                            .addComponent(linearButton)
                            .addComponent(smoothButton)
                            .addComponent(histEqButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNameLabel)
                            .addComponent(startOverButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(fileErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadButton)
                .addContainerGap())
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(fileErrorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(linearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(smoothButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(histEqButton)
                .addGap(18, 18, 18)
                .addComponent(startOverButton)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Description: This method fetches the string from the text box and 
     * calls the loadFile method of the PgmImage originalImage.
     * This is an event handler method for the Load button.
     * @param evt a mouse clicked event
     */
    private void loadButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadButtonMouseClicked
        String fileName = fileNameTextField.getText();
        originalImage.loadFile(fileName);
        if (originalImage.image == null) {
            fileErrorLabel.setVisible(true);
        } else {
            fileErrorLabel.setVisible(false);
            fileNameLabel.setVisible(false);
            fileNameTextField.setVisible(false);
            loadButton.setVisible(false);
            displayButton.setVisible(true);
            smoothButton.setVisible(true);
            linearButton.setVisible(true);
            histEqButton.setVisible(true);
            startOverButton.setVisible(true);
            originalImage.displayImage(this, imageLabel);
        }
    }//GEN-LAST:event_loadButtonMouseClicked
    /**
     * This is the event handler for the Display button.  It displays the 
     * original image.
     * @param evt a mouse clicked event
     */
    private void displayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayButtonMouseClicked
        originalImage.displayImage(this,  imageLabel);
    }//GEN-LAST:event_displayButtonMouseClicked
    
    /**
     * A histogram is just a count of values.  To count the gray values in 
     * an image you need a place to store 256 values. For each pixel in the 
     * original image, increment that location in the histogram array. Once 
     * those values are gathered you need to accumulate the sums of the 
     * histograms in this manner: 
     *    sums[0] = histograms[0] then for each element in the sums array 
     *    sums[i] = sums[i-1] + histograms[i]
     * 
     * @param evt The mouse clicked event
     */
    private void histEqButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_histEqButtonMouseClicked
        
    }//GEN-LAST:event_histEqButtonMouseClicked

    /**
     * Smoothing an image is quite easy.  For each pixel in the original image,
     * calculate the average of that pixel and its eight neighbors in the 
     * 2D array. The corresponding pixel in the smoothed image gets that 
     * average.  You do NOT need to worry about the edges
     * @param evt The mouse clicked event
     */
    
    private void smoothButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smoothButtonMouseClicked

    }//GEN-LAST:event_smoothButtonMouseClicked
    /**
     * Linear Enhancement makes the features within an image more visible. 
     * It does this by increasing the range of values within the image 
     * which increases the contrast.  It involves:
     * 1. Finding the largest and smallest values within the image 
     *      (gray scale values are from 0 - black to 255 - white)
     * 2. Computing a scaling factor based on the min and max 
     *      scale = (255.0 / (max-min))
     * 3. Changing each pixel value by subtracting the minimum and then 
     * multiplying by the scaling factor (guarantees some black or almost 
     * black pixels and some white or whiter pixels).
     * @param evt The mouse clicked event
     */
    private void linearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linearButtonMouseClicked
        
    }//GEN-LAST:event_linearButtonMouseClicked
    
    
    private void startOverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startOverButtonMouseClicked
        fileNameTextField.setVisible(true);
        fileNameTextField.setText("");
        fileNameLabel.setVisible(true);
        loadButton.setVisible(true);
        fileErrorLabel.setVisible(false);
        displayButton.setVisible(false);
        smoothButton.setVisible(false);
        linearButton.setVisible(false);
        histEqButton.setVisible(false);
        startOverButton.setVisible(false);
        PgmImage blankImage = new PgmImage(); 
        blankImage.makeBlankImage(originalImage.width,
                originalImage.height,  190);
        blankImage.displayImage(this, imageLabel);
    }//GEN-LAST:event_startOverButtonMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton displayButton;
    private javax.swing.JLabel fileErrorLabel;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JButton histEqButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton linearButton;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton smoothButton;
    private javax.swing.JButton startOverButton;
    // End of variables declaration//GEN-END:variables
    private PgmImage originalImage = new PgmImage();

}
