
package palidromegui;

/**
 *
 * @author kalalajoel
 */
public class PalidromeUi extends javax.swing.JFrame {

    /**
     * Creates new form PalidromeUi
     */
    public PalidromeUi() {
        initComponents();
        doAnotherButton.setVisible(false);
        orginalInputLabel.setVisible(false);
        resultsLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        CheckitButton = new javax.swing.JButton();
        doAnotherButton = new javax.swing.JButton();
        inputTextField = new javax.swing.JTextField();
        inputLabel = new javax.swing.JLabel();
        orginalInputLabel = new javax.swing.JLabel();
        resultsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Palindrome")));

        CheckitButton.setText("Check it");
        CheckitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckitButtonMouseEntered(evt);
            }
        });

        doAnotherButton.setText("Do again");
        doAnotherButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doAnotherButtonMouseClicked(evt);
            }
        });

        inputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextFieldActionPerformed(evt);
            }
        });

        inputLabel.setText("Enter a word or phrase below ");

        orginalInputLabel.setText("Orginal inuput ");

        resultsLabel.setText("Results label");

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(inputLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(inputTextField))
                .addContainerGap())
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orginalInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(resultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)))
                .addComponent(doAnotherButton)
                .addGap(35, 35, 35))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputLabel)
                .addGap(9, 9, 9)
                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doAnotherButton)
                    .addComponent(CheckitButton))
                .addGap(43, 43, 43)
                .addComponent(orginalInputLabel)
                .addGap(29, 29, 29)
                .addComponent(resultsLabel)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTextFieldActionPerformed

    private void doAnotherButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doAnotherButtonMouseClicked
      doAnotherButton.setVisible(false);
      orginalInputLabel.setVisible(false);
      resultsLabel.setVisible(false);
      CheckitButton.setVisible(true);
      inputTextField.setText("");
      inputTextField.setVisible(true);
      
      
    }//GEN-LAST:event_doAnotherButtonMouseClicked

    private void CheckitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckitButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckitButtonMouseEntered

    private void CheckitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckitButtonMouseClicked
       String s =  inputTextField.getText();
       //String l =s.toLowerCase();
       
    // The index of the first character in the string
    
    StringBuilder str = new StringBuilder();
    for(int i = 0; i < s.length(); i++){
        if (Character.isLetter(s.charAt(i))){
            str.append(s.charAt(i));
        }
    }
     String l =str.toString().toLowerCase();
     int low = 0;

    // The index of the last character in the string
    int high = l.length() - 1;
     
       boolean isPalindrome = true;
    while (low < high) {
      if (l.charAt(low) != l.charAt(high)) {
        isPalindrome = false;
        break;
      }

      low++;
      high--;
    }

    if (isPalindrome){
     resultsLabel.setText(s + " is a palindrome");
    } else{
          resultsLabel.setText(s + " is not a palindrome");
}
  orginalInputLabel.setText(s);
        inputLabel.setVisible(false);
         inputTextField.setVisible(false);
         doAnotherButton.setVisible(true);
           CheckitButton.setVisible(false);
             orginalInputLabel.setVisible(true);
             resultsLabel.setVisible(true);
        
    }//GEN-LAST:event_CheckitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PalidromeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PalidromeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PalidromeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PalidromeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PalidromeUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckitButton;
    private javax.swing.JButton doAnotherButton;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel orginalInputLabel;
    private javax.swing.JLabel resultsLabel;
    // End of variables declaration//GEN-END:variables
}
